# Generated by Django 4.1.3 on 2022-11-28 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateSignedUp',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='user',
            name='on_dialysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.IntegerField(default=4),
        ),
    ]
