# Generated by Django 4.1.3 on 2022-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='k_pdv',
        ),
        migrations.RemoveField(
            model_name='food',
            name='na_pdv',
        ),
        migrations.RemoveField(
            model_name='food',
            name='phos_pdv',
        ),
        migrations.AddField(
            model_name='food',
            name='serving_size_unit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='k_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='na_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='phos_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protien_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
