# Generated by Django 4.1.3 on 2022-12-01 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default=datetime.time(10, 7, 5, 931899)),
        ),
    ]
