# Generated by Django 4.1.3 on 2022-12-01 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default=datetime.time(13, 1, 8, 132604)),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(),
        ),
    ]
