# Generated by Django 4.1.3 on 2022-12-02 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0002_alter_entry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time',
            field=models.TimeField(default=datetime.time(18, 32, 57, 816671)),
        ),
    ]
