# Generated by Django 4.1.3 on 2022-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0003_rename_datesignedup_user_date_signed_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stage',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
