# Generated by Django 4.1.3 on 2022-11-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0004_alter_user_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='albumin_level',
            field=models.DecimalField(decimal_places=2, default=3.5, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_sugar_level',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='user',
            name='creatinine_level',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='k_level',
            field=models.DecimalField(decimal_places=2, default=4.4, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='na_level',
            field=models.PositiveSmallIntegerField(default=140),
        ),
        migrations.AddField(
            model_name='user',
            name='phos_level',
            field=models.DecimalField(decimal_places=2, default=3.65, max_digits=4),
        ),
    ]
