# Generated by Django 4.1.3 on 2022-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kidneyfoundation', '0005_user_albumin_level_user_blood_sugar_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
